## template: jinja
#cloud-config
---

packages:
  - ["consul", "1.12.*"]
  - ["nomad",  "1.3.*"]
  - ["containerd.io", "1.6.*"]

package_update: true
package_upgrade: true
package_reboot_if_required: true
